### ISSUE TITLE
Support for STM32L0

### ISSUE THREAD

**Issue by mattwilliamson** [jpnorair/OpenTag#11]
Cortex M0+ support would be nice to get even lower power during run mode using LPTIM1.

**Comment by jpnorair** [comment]
In the experimental branch, there should be some early support for STM32L0.  I had some trouble getting interrupts to work, but once that is fixed, it should work.  I haven't kept-up the STM32L0 support given that the STM32L4 just came out, and that might offer the better roadmap as far as ST is concerned.

**Comment by jpnorair** [comment]
All done.  Check experimental branch.
